# -*- coding: utf-8 -*-
"""Final plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NMQUdEmMT0J77IjlXedu_jpQG8Bu5p41
"""

#Reading filename 2.text that contains the applications and the various permissions associated with the applications
with open("/content/filename 2.txt") as f:
     data = f.readlines()

#Creating a dictionary of the application name vs the number of permissions associated with a particular application
dict1={}
for i in range(len(data)):
  if i%2==0:
    val = data[i]
    if data[i] in dict1.keys():
      dict1[val] +=1
    else:
      dict1[val] = 1

#creating a dictionary with the number of permissions as the key and value as the number of applications having a specific number of permissions
dict2={}
for v in dict1.values():
  if v in dict2.keys():
    dict2[v] +=1
  else:
    dict2[v] =1
print(dict2)

x_axis = []
y_axis = []
for i in sorted(dict2.keys()):
    x_axis.append(i)
    y_axis.append(dict2[i])
plt.plot(x_axis, y_axis)
plt.title('Line Chart')
plt.xlabel('No of permissions')
plt.ylabel('No of Apps with a specific permission')
plt.show()